INSERT INTO burgers(burger_name) VALUES ("double double burger")
INSERT INTO burgers(burger_name) VALUES ("classic burger")
INSERT INTO burgers(burger_name) VALUES ("chicken burger")
INSERT INTO burgers(burger_name) VALUES ("double western bacon chees burger")
INSERT INTO burgers(burger_name) VALUES ("protien style burger")